name: Main

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Tests and linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the 0.6.2 version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.2"
    - name: Install dependencies
      run: |
        uv sync
        uv pip install -e ".[dev]"
    - name: Run tests
      run: |
        uv run pytest
    - name: Run linter
      run: |
        uv run ruff check .